### ISSUE TITLE
Disabaling the crates.io proxy will not disable the sparse index

### ISSUE THREAD

**Issue by Christiaan676** [kellnr/kellnr#297]
When testing I noticed that the index data would download correctly but downloading the crates resulted in a 404 as the crates.io proxy function was disabled. Looking at the code, confirms this. As only the download function in cratesio_api.rs checks the Proxy.enabled flag.

Most logical solution to me would be to restructure the main function. And create init functions for the different system components. The crates.io proxy function can than be surrounded by an if statement controlled by the configuration.

**Comment by guzzijones** [comment]
So yes.  setting `Proxy.enabled = False` will allow the index to be checked with `cargo search` , but `cargo add` will try to pull the package and then kellnr will proxy to the internet instead of using it's local store.

In our case the machine cannot reach the internet so we see these pod logs when pulling our local `chrono` crate: 
```
2024-04-23T21:39:58.675736Z ERROR index::cratesio_prefetch_api: Error fetching prefetch data from \
 crates.io: error sending request for url (https://index.crates.io/au/to/autocfg): error trying to connect: \ 
dns error: failed to lookup address information: Temporary failure in name resolution  
```

**Comment by guzzijones** [comment]
It actually looks like proxy.enabled = false will prevent all downloads.

**Comment by guzzijones** [comment]
to clarify - we are publishing cratesio packages to kellnr and they are not found when it goes to download them

**Comment by secana** [comment]
Fix will be in the next Kellnr release.
